version: '3.8'

services:
  traefik-test:
    image: 'traefik:latest'
    command:
      - '--api.insecure=true'
      - '--providers.docker=true'
      - '--providers.docker.exposedbydefault=false'
      - '--providers.docker.network=proxy'
      - '--entrypoints.web.address=:80'
      - '--entrypoints.web.http.redirections.entrypoint.to=websecure'
      - '--entrypoints.web.http.redirections.entrypoint.scheme=https'
      - '--entrypoints.websecure.address=:443'
      - '--certificatesresolvers.le.acme.tlschallenge=true'
      - '--certificatesresolvers.le.acme.storage=/letsencrypt/acme.json'
      - '--certificatesresolvers.le.acme.caServer=https://acme-staging-v02.api.letsencrypt.org/directory'
    ports:
      - '80:80'
      - '443:443'
      - '8090:8080'
    volumes:
      - 'certs:/letsencrypt'
      - '/var/run/docker.sock:/var/run/docker.sock:ro'

  test_proxy:
    image: nginx:1.19-alpine
    volumes:
      - ./test-proxy/conf.d:/etc/nginx/conf.d:ro
    ports:
      - '3030:80'

  file_server:
    image: nginx:1.19-alpine
    volumes:
      - ./nginx:/etc/nginx:ro
      - 'storage:/media/data'
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.${SATNAME}_files.rule=Host(`${SATNAME}.${DOMAIN}`)'
      - 'traefik.http.routers.${SATNAME}_files.entrypoints=websecure'
      - 'traefik.http.routers.${SATNAME}_files.tls.certresolver=le'

  app_server:
    build: ./server
    environment:
      # - APIKEY=${APIKEY}
      - SATNAME=${SATNAME}
    volumes:
      - 'storage:/media/data'
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.services.${SATNAME}_app.loadbalancer.server.port=3000'
      - 'traefik.http.routers.${SATNAME}_app.rule=Host(`${SATNAME}.${DOMAIN}`) && PathPrefix(`/graphql`)'
      - 'traefik.http.routers.${SATNAME}_app.entrypoints=websecure'
      - 'traefik.http.routers.${SATNAME}_app.tls.certresolver=le'
      - 'traefik.http.routers.${SATNAME}_app.middlewares=corsHeaders'
      - 'traefik.http.middlewares.corsHeaders.headers.accessControlAllowMethods=GET,OPTIONS,PUT'
      - 'traefik.http.middlewares.corsHeaders.headers.accessControlAllowOrigin=*'
      - 'traefik.http.middlewares.corsHeaders.headers.accessControlAllowHeaders=*'

  alpha:
    image: dgraph/dgraph:latest
    volumes:
      - dgraph_data:/dgraph
    ports:
      - '8080:8080'
    command: dgraph alpha --my=alpha:7080 --zero=Zero:5080 --graphql_extensions=false --whitelist 0.0.0.0/0

  zero:
    image: dgraph/dgraph:latest
    volumes:
      - dgraph_data:/dgraph
    command: dgraph zero --my=zero:5080

volumes:
  dgraph_data:
  certs:
  storage:
