version: '3.8'

services:
  web_proxy:
    image: nginx:1.19-alpine
    volumes:
      - ./nginx:/etc/nginx:ro
      - 'storage:/media/data'
    networks:
      stack:
      proxy:
    deploy:
      labels:
        - 'traefik.enable=true'
        - 'traefik.http.services.${SATNAME}.loadbalancer.server.port=80'
        - 'traefik.http.routers.${SATNAME}.rule=Host(`${SATNAME}.${DOMAIN}`)'
        - 'traefik.http.routers.${SATNAME}.entrypoints=websecure'
        - 'traefik.http.routers.${SATNAME}.tls.certresolver=le'
        - 'traefik.http.routers.${SATNAME}.middlewares=corsHeaders'
        - 'traefik.http.middlewares.corsHeaders.headers.accessControlAllowMethods=GET,OPTIONS,POST'
        - 'traefik.http.middlewares.corsHeaders.headers.accessControlAllowOrigin=*'
        - 'traefik.http.middlewares.corsHeaders.headers.accessControlAllowHeaders=*'

  app_server:
    image: 'satellitebaas/core-server'
    environment:
      - APIKEY=${APIKEY}
      - SATNAME=${SATNAME}
    volumes:
      - 'storage:/media/data'
    networks:
      stack:
      backend:
        aliases:
          - app_${SATNAME}

  alpha:
    image: dgraph/dgraph:latest
    volumes:
      - dgraph_data:/dgraph
    networks:
      stack:
    command: dgraph alpha --my=alpha:7080 --zero=zero:5080 --graphql_extensions=false --whitelist 0.0.0.0/0

  zero:
    image: dgraph/dgraph:latest
    volumes:
      - dgraph_data:/dgraph
    networks:
      stack:
    command: dgraph zero --my=zero:5080

volumes:
  dgraph_data:
  storage:

networks:
  stack:
  backend:
    external: true
  proxy:
    external: true
